### ISSUE TITLE
Messy DeltaBot Situation 

### ISSUE THREAD

**Issue by Snorrrlax** [MystK/delta-bot-three#42] opened 2016-10-02 13:08 UTC
See this thread: https://www.reddit.com/r/changemyview/comments/55f6yq/cmv_as_a_girl_theres_no_advantage_for_me_to_date/d8a3q61

Firstly, the OP edits a delta into their comment, which as we know isn't awarded unless a mod is aware (hence the priority with that issue). So then they make a new comment containing only a delta symbol, which DeltaBot rightly rejects under normal circumstances, but there are two issues:

1) DeltaBot replies three times to the same comment.
2) Two of the replies are undistinguished.

Obviously the undistinguished thing doesn't matter since those two replies weren't needed anyway, but I wonder if it's because of a bug that might have a wider effect?

**Comment by MystK** [comment] 2016-10-02 16:23
Pretty sure this is a duplicate of #28. Fixing #28 would fix this.

**Comment by RaoulMeyer** [comment] 2017-01-28 23:44
As this issue is a duplicate of #28, this should be closed.

**Closed by RaoulMeyer** 2017-01-28 23:44 UTC
Labels: bug
