### ISSUE TITLE
Missed Delta

### ISSUE THREAD

**Issue by Snorrrlax** [MystK/delta-bot-three#202] opened 2017-07-17 17:11 UTC
We received a message saying that this delta had been missed: https://www.reddit.com/r/changemyview/comments/6mv6te/cmv_upon_plane_arrival_departing_passengers_in/dk4pxuv/

We used the add command to deal with it, but is there a way to find out how this happened?

**Comment by MystK** [comment] 2017-07-17 17:24
Hmm, I have some ideas on how this was missed if this was an edit.

I think we only have 1 edit thread going, but 3 normal comment threads.

**Comment by Snorrrlax** [comment] 2017-07-26 10:58
Another one: https://www.reddit.com/r/changemyview/comments/6pgdki/cmv_in_a_free_exchange_of_goods_with_adequate/dkp6026/

**Comment by mchav** [comment] 2017-08-21 01:40
Both comments seem to have deltas now? How can I reproduce the issue?

**Comment by acz13** [comment] 2017-10-07 21:42
This was an edit issue, right? I suppose this should be fixed by periodically checking the `/about/edited` api endpoint?

**Comment by MystK** [comment] 2017-10-10 15:48
Yup, we actually already check the /about/edited endpoint. It seems like an intermittent issue which I believe happens only on Reddit overload.

**Comment by MystK** [comment] 2018-03-10 06:48
closing for now because a lot of refactoring was done to the code

**Closed by MystK** 2018-03-10 06:48 UTC
Labels: bug
