### ISSUE TITLE
User reports seeing the hidden text on iPhone reddit app

### ISSUE THREAD

**Issue by hacksoncode** [MystK/delta-bot-three#21] opened 2016-07-08 20:20 UTC
A user (https://www.reddit.com/user/el3r9) has reported that they can see the hidden text on a delta message in the iOS reddit app. Here's the comment where they mention it... 

https://www.reddit.com/r/changemyview/comments/4rmxwp/cmv_you_cant_be_a_social_democrat_fiscal/d52mv4x

Wasn't sure whether you were ok with my sending random people your username for things like this.

**Comment by JohnnyO** [comment] 2016-07-08 21:48
Confirmed, I just checked it in the Reddit app, screenshot is below

https://imgur.com/a/spjqY

**Comment by MystK** [comment] 2016-07-09 04:35
Thanks! Glad I put that comment there. :) please forward all issues to this repo and I'll knock them all out!

**Comment by MystK** [comment] 2016-07-16 17:39
Did some investigating. Not a bug with DB3. It is due to the Reddit app. It does not correctly support markdown. Normally I'd just close this out, but I will leave this open as I will try to work around the Reddit app's bug.

**Comment by hacksoncode** [comment] 2016-07-16 17:54
I wonder if it's because of the empty brackets... Maybe try using the
period at the end of the sentence as the "link text"?

-- 
Ray

**Comment by MystK** [comment] 2016-07-16 19:53
Pretty sure you're spot on! That + maybe the new line characters.

**Comment by MystK** [comment] 2016-07-16 19:58
Thanks hacksoncode. Added a "." inside of the "[]" and it worked!

**Closed by MystK** 2016-07-16 19:58 UTC
