### ISSUE TITLE
Monthly deltaboard score reduced

### ISSUE THREAD

**Issue by Snorrrlax** [MystK/delta-bot-three#198] opened 2017-05-21 20:18 UTC
u/Ansuz07's delta count keeps lowering on the monthly deltaboard. I think it was at 14 a day ago, then 12, and now it's at 9. I can't provide any more information unfortunately, but none of us are sure what's going on.

**Comment by mchav** [comment] 2017-08-21 01:42
Any leads for why this might be the case? Also it would be great to get some documentation going to reuce ramp up time for new contributors.

**Comment by Snorrrlax** [comment] 2017-09-27 14:49
This mod post contained another example of this problem: https://www.reddit.com/r/changemyview/comments/6o2smk/mod_post_looking_for_help_with_our_deltaboard/

**Comment by nshiff** [comment] 2017-10-16 09:18
@mchav According to the thread linked by Snorrrlax, user MNGrrl writes: "I think the bug is in the date comparison logic when its deciding what month it is." I recommend reading the linked thread. There is a back-and-forth with MystK.

Personally, to look into this further, it would be helpful to know: 

Which users are affected, just this one? 

In addition to the wrong delta count, what is the expected delta count? 

... can you please link me to the place where I see the issue? ha ha. I am not familiar with the scoreboard.

**Comment by Snorrrlax** [comment] 2017-10-30 14:18
It's happening again just now (Ansuz07 has reduced from 14 to 10 in the monthly deltaboard). 

@nshiff sorry for the delay in responding, but I'm not sure exactly how to answer your questions and was hoping someone with knowledge of the code could help. I'm not aware of any pattern, I just occasionally notice some users slipping down the ranks when they shouldn't be. 

You'll be able to see it in the sidebar over at r/changemyview (the strip of text on the right), or at https://www.reddit.com/r/changemyview/wiki/deltaboards.

**Comment by MystK** [comment] 2018-03-10 06:53
closing and further discussion will be in #232  because that is the root cause

**Closed by MystK** 2018-03-10 06:53 UTC
Labels: bug
