### ISSUE TITLE
Upgrade server (?)

### ISSUE THREAD

**Issue by hacksoncode** [MystK/delta-bot-three#223] opened 2018-01-06 21:33 UTC
There has been discussion about upgrading the server to a higher class of VM. 

This is a place for discussions/decisions about exactly what we need, why, etc.

I'll close it either by upgrading the server or if we decide not to do so.

**Comment by wyantb** [comment] 2018-01-07 00:48
It's mostly me arguing for this, in #207, so I'll summarize my reasoning. Thoughts from @MystK also welcome. I think we should move to a larger instance so that we can have the disk space to write out a database using `leveldb` (see https://github.com/MystK/delta-bot-three/pull/222 ). A `2GB SVZS` would give the bot plenty of room to grow, and might even help reliability/deployability (we could `yarn install` more dependencies on a larger box without worrying about memory issues when loading too many libraries or running out of hard disk space for all the dependencies).

You're welcome to try a 1GB svzs as well, see how it runs and whether or not there's any signs we need to try a larger instance to start with.

**Comment by MystK** [comment] 2018-01-07 03:49
I'm not too familiar with the specs we require to run a database with DB3, but I agree that we need a database, and if it means we need a larger server, I think it's necessary.

I've already ran into issues of installing dependencies that @wyantb is talking about also, and it becomes especially hard when we're dealing with compiling on windows and deploying to linux servers. A larger server would allow us to compile and deploy on the same server.

**Comment by mitchell271** [comment] 2018-01-07 04:24
I've finally got time to actually work on this project. Are things hosted on AWS ATM? An RDS instance would solve this issue.

**Comment by wyantb** [comment] 2018-01-07 17:44
hacks has mentioned that the current server is running on RamNode, so I've tended to compare prices using their plans https://www.ramnode.com/vps.php . i.e. no, not on AWS right now. An RDS instance, even at the t2.micro levels, seems to bottom out around $10 per month just for the DB. Personally I don't think we need an external DB, see my proposal for initial integration with an on-disk one in https://github.com/MystK/delta-bot-three/pull/222

**Comment by mitchell271** [comment] 2018-01-08 02:02
Gotcha. Considering the size of the sub and the amount of activity the bot
has, 1GB svzs should enough for a while imo. If it's on disk, and there's
worry about portability when/if migrating to a larger instance, why not
wrap it in a Docker container with a companion Redis container? I realize
that's more overhead (and potentially unneeded work), but it would allow
for more flexibility.

**Comment by MystK** [comment] 2018-01-08 19:03
@mitchell271 are you suggesting having two VM instances? One with docker that we can easily migrate which interfaces through the network with a second VM redis instance which cannot be easily migrated?

**Comment by mitchell271** [comment] 2018-01-08 19:08
Sorry, should've been more specific. I meant wrap the DB in a container. It could run on the same VM, but allow for easy expansion if needed in future. 

So single VM with an on disk DB, with the DB in a container. The bot could be put in a container at a later date as well. That said, if I'm completely jumping the gun, feel free to ignore all of this.

**Comment by MystK** [comment] 2018-01-08 21:27
@wyantb has already introduced a database called level and it is actually part of the node application, but I think dockerizing the environment would be helpful for easily migrating from instance to instance, although I don't know how we'll handle the database. If you're willing to take up the project of dockerizing DB3 and handling the database migrations, it would be much appreciated.

**Comment by hacksoncode** [comment] 2018-01-08 21:43
If it helps any... if we update DeltaBot to use a bigger instance because it needs a database, I think it would be a "nice to have" if that were an option that someone could turn off...

We occasionally get asked if someone can use the bot code, and not everyone will want all the spiffy features if it actually costs them significant money. 

But that's definitely optional if it complicates the design too much. 

Thanks for having the discussion, guys... make a proposal for what you decide and what the cost impact would be, and I'll either just buy the new instance, or if it seems to expensive I'll put it up for a vote by the other mods to see if they want to pitch in.

**Comment by wyantb** [comment] 2018-01-09 02:16
@hacksoncode Do you have any active examples of other folks actively using the bot code for other subreddits/purposes? I imagine that would be fairly difficult with all the other features that are hardcoded, sticky responses etc. I figure they would need to fork the project anyway, which is best done by someone who knows how to rip out irrelevant code. To help folks with that in the future, we could certainly add a branch/tag to the last versions before the database to make it especially obvious where the fork happened.

Otherwise...

From my (very little) knowledge of docker, I have no blocking concerns. Per https://www.quora.com/What-is-the-minimum-memory-reqirement-to-run-Docker etc, I don't think we would need a larger RamNode instance than the 1GB already proposed to let it get up and running. 

My only worry is about adding more overhead to the coding & testing processes for maintainers of the library - there's already a steep curve to hopping on board this thing, and there's only a handful that have been able to make significant changes to it. If docker only affects deploying the bot, and not the expected dev cycle, though, this point is moot.

So, again, my comments are certainly not blocking any adoption of docker. But, for the sake of argument, I'll propose & vote for the option: let's migrate to a `1GB SVZS` instance, with an on-disk DB, and plan on doing a `rsync`/`s3cmd sync` operation to backup the DB.

**Comment by wyantb** [comment] 2018-01-09 02:18
Oh, right...

> it is actually part of the node application, but I think dockerizing the environment would be helpful for easily migrating from instance to instance

I agree with MystK's comments here. If we stick with `level` (the on-disk DB) and opt for docker, we could just write to the writeable layer of the container and call it a day.

**Comment by hacksoncode** [comment] 2018-01-09 03:19
>@hacksoncode Do you have any active examples of other folks actively using the bot code for other subreddits/purposes?

Well it happened with each of the previous 3 instantiations of DeltaBot... but maybe that ship has sailed as far as easily being able to do it with the current version. As I said, it's not a requirement, just a nice-to-have. 

But by all means have a vote and let me know what to do, and when.

**Comment by mitchell271** [comment] 2018-01-09 03:30
I can do the docker implementation. I introduced it to our stack at my
previous job, so I feel like I've got at least a bit of a handle on it.
Plus, because I'm not super familiar with the codebase, it would give me a
chance to learn parts of it and which are the most crucial. Absolute worst
case, docker stuff goes nowhere or we have someone used to managing swarms
take it over in future.

**Comment by Snorrrlax** [comment] 2018-01-11 01:40
@MystK do you have a decision on this? Hacks can then move forward with what you and @wyantb suggest.

**Comment by Snorrrlax** [comment] 2018-01-20 13:48
@hacksoncode shall we go with @wyantb's suggestion? Then we can merge his PR.

**Comment by hacksoncode** [comment] 2018-01-20 21:20
To double check my understanding: 

The proposal is to buy a RamNode 1024MB OpenVZ SSD VPS (SVZS) instance.

The team will handle the task of migrating DeltaBot (and I guess the new ModBot?) there. 

Is that correct? 

I am ok with covering the price of that myself ($3.5/month). 

I'll do that as soon as MystK approves.

**Comment by MystK** [comment] 2018-01-22 23:04
Thumbs up from me and thanks @hacksoncode. I know it's an arm and a leg compared to the original price. ;)

**Comment by hacksoncode** [comment] 2018-01-22 23:46
Forgot to ask:

I need to verify which of their supported OS's we want installed (old one was CentOS 6 64-bit).

Also, though I don't think this is too critical, what the server name should be. I still have the hopto.org account for my own purposes, so I can add another DDNS link there. Maybe CMVBot.hopto.org in case we decide to host the CMVModBot there some day, too?

**Comment by wyantb** [comment] 2018-01-22 23:51
I don't think the server OS matters too much - as long as the most recent
version of node supports it. I'm sure cent is fine if it was what you were
using before.

Brian Wyant (Phone)

**Comment by MystK** [comment] 2018-01-22 23:57
agree with @wyantb that any OS is fine but the same version as before would make it easier for me to redeploy and set everything up.

The server name makes no difference to me so whatever you want to name it to future proof it.

**Comment by hacksoncode** [comment] 2018-01-23 00:03
Ok, it's bought and live. Hostname is CMVBot.hopto.org. Same account as the old machine, so you guys should have access. Let me know if that assumption turns out to be wrong (and preferably what I need to do to fix it :-).

**Comment by Snorrrlax** [comment] 2018-01-23 00:05
@perezdev What are your thoughts on CMVModBot sharing with DeltaBot here?

**Comment by hacksoncode** [comment] 2018-01-23 00:13
I guess one detail is the login details... I think the solusVM client page probably will still work with the old account information, but I've totally forgotten/lost the password for that. The username they're showing for that account is RNuser48305... I don't remember if that's the same one. 

Anyway, let me know how to send the temporary password to what "responsible party" (MystK, I assume), and by what method.

**Comment by MystK** [comment] 2018-01-23 00:15
I have the password for RNuser48305 and can provide to @perezdev. I think it's different credentials for each VM though but I may be wrong. I will check tonight.

**Comment by perezdev** [comment] 2018-01-23 03:55
@Snorrrlax @MystK I'm good with whatever solution we want to go with. I was originally planning on hosting the bot on Azure. But it looks like we want to go with RamNode?  The bot requires Windows on .NET Framework 4.6. Will that be a problem?

**Comment by hacksoncode** [comment] 2018-01-23 03:59
Sounds like that's not a good match. It's unfortunate that we have bots running on relatively incompatible systems, but that's the way the cookie tracks you :-).

**Comment by MystK** [comment] 2018-01-23 05:16
My bot can run on any OS so if we choose to go with Windows that’s fine, but from my experience it’s pretty expensive.

Antoine
________________________________

**Comment by MystK** [comment] 2018-01-23 18:20
Just checked the logon and I can confirm I have access to both of the VMs. I'll do the migration this week.
________________________________

**Comment by MystK** [comment] 2018-01-24 19:47
I completed migration of the old server to the new server and verified that everything is working in production. @hacksoncode you can now cancel the old server.

The last step before closing this ticket is moving the staging server from my own personal ramnode server to the new server hacksoncode made since now there is more bandwidth.

**Comment by Snorrrlax** [comment] 2018-01-24 20:28
Nice!

Is there any way DeltaBot can align with @perezdev's CMVModBot here?

**Comment by MystK** [comment] 2018-01-24 21:42
align as in use the same environment? Yes DB3 can run on any environment, so if you guys have a machine that is compatible with @perezdev 's bot, I can migrate it over there. Just say the word.

I've successfully moved staging to the new environment and will now be closing this ticket.

**Closed by MystK** 2018-01-24 21:42 UTC
Labels: discussion, enhancement

**Comment by Snorrrlax** [comment] 2018-01-24 22:11
Okay, I'm not really sure what that means, but hopefully @hacksoncode, @perezdev, @wyantb and yourself can liaise on this.

**Comment by perezdev** [comment] 2018-01-24 23:18
@MystK @Snorrrlax I'll need to test on a Windows RamNode to make sure it'll work. I imagine it will though

**Comment by MystK** [comment] 2018-01-25 17:52
From my searching Ramnode only supports Windows Server 2008 R2 Web (x86_64) and we would need to upgrade our instance again. I'm not too familiar with Windows on Ramnode, but I wouldn't think it has good support. It might be good to explore other options also.
________________________________

**Comment by perezdev** [comment] 2018-01-25 18:49
It might be good to just stick with Azure then since it's free and supports the app. It's one more system to manage, but free is always good. Although we'll have to re-evaluate it if we exceed the free parameters. But it doesn't look like we will from my initial review.

**Comment by MystK** [comment] 2018-01-25 18:52
I was under the impression that Azure Virtual Machines did not have a free tier. Are you using that or a different Azure service?

**Comment by perezdev** [comment] 2018-01-25 19:37
I'm running it as a WebJob. I did an initial test a month or so ago and it seemed to work okay. No I just need to make sure the full bot works now.

**Comment by hacksoncode** [comment] 2018-02-25 19:37
Just cancelled the old server.

**Comment by MystK** [comment] 2018-02-25 19:38
Congrats to the official move to the new server!

Antoine
________________________________
