### ISSUE TITLE
DB was not awarding deltas for 13 hours, had to reboot server

### ISSUE THREAD

**Issue by hacksoncode** [MystK/delta-bot-three#233] opened 2018-02-25 19:39 UTC
We should try to get to the root cause of why it's hanging/stopping awarding. 

Did we ever create a management console for easier/more effective restarting of the bot as opposed to just rebooting the whole VM? I think there was an issue about that, but I'm not seeing it at first glance.

Also, I'm not sure if there's anything else running that doesn't autostart... I would assume not, but let me know.

**Comment by wyantb** [comment] 2018-02-25 19:41
Poop. If this wasn't happening before `level` db usage, that's a fair first guess as to the cause. (The other fair first guess would be something about the VM/node version...could test those out by using an old build of the bot on the current system). 

Got logs from the bot preceding the shutdown?

**Comment by hacksoncode** [comment] 2018-02-25 19:47
Sorry, unfortunately, I don't know how to get logs from the bot... it was a somewhat emergency situation as lots of deltas were being missed. 

What is the procedure for that?

**Comment by hacksoncode** [comment] 2018-02-25 19:49
Hmmmm... actually, though... it doesn't seem to be working on the backlog yet, since I restarted the VM 10 minutes ago... does something else need to be done, or is that an expected delay?

**Comment by MystK** [comment] 2018-02-25 19:49
I might be able to whip up a super fast management console with logs and reboot buttons.

**Comment by hacksoncode** [comment] 2018-02-25 20:13
Other mods are saying that DB never caught up to the backlog the last time this happened, either. Can we just use this bug for investigating why that is? Or should this stay limited to why it hangs and a new bug entered about not catching up on reboot?

**Comment by hacksoncode** [comment] 2018-02-25 21:32
BTW, DB is still having no activity, even in response to manual add commands. 

Something is seriously wrong with our little friend.

**Comment by MystK** [comment] 2018-02-25 21:54
On the road. Someone needs to ssh into the server and manually start DB3. I might have not added auto start on reboot.

Log in as db3 user
Cd to delta-bot-three
Nvm use
Npm run startProduction

I will be home in like 2-3 hours if anything


Antoine
________________________________

**Comment by hacksoncode** [comment] 2018-02-25 23:38
Well, damn... it turns out that I can't find the password for any accounts on the new server that work.

**Comment by MystK** [comment] 2018-02-25 23:39
Restarted it. It’s working now. On the road and will check it out again when I get home.

Antoine
________________________________

**Comment by MystK** [comment] 2018-02-26 00:35
So something is definitely up with the server. I wasn't able to get it working on the virtual machine and am running production on my computer at the moment. I'll be spending today to figure out what's exactly wrong and to see if I can improve reliability.

**Comment by MystK** [comment] 2018-02-26 00:35
Also apologies from my side. I think DB3 has been unstable recently because I have been pushing changes to production without thoroughly testing it in staging. I think there are issues with the automatic deployment at the moment. That is the root cause.

**Comment by MystK** [comment] 2018-03-02 19:03
closing because I'm pretyt sure this was my fault.

**Closed by MystK** 2018-03-02 19:03 UTC
